from langchain_core.prompts import ChatPromptTemplate
from typing import Tuple

def get_cover_image_prompt(content_type: str) -> ChatPromptTemplate:
    """
    Creates a prompt template to generate a high-quality IMAGE PROMPT for a 
    text-to-image model and a separate negative prompt string.
    This is tailored for models like Amazon Titan Image Generator ("nova canvas")
    which accept a dedicated negative prompt.

    Returns:
        A ChatPromptTemplate for the text generation model.
    """

    # Persona for the LLM that is generating the image prompt
    persona_prompt = """
    <persona>
        You are an expert prompt engineer specializing in creating very very very detailed prompts for morder vector art, cartoon style, cartoon style cover images for articles. 
        Image generated by your prompt Must be revealing the main topic of the article.

        **Style:** Modern vector art, cartoon style, cartoon style.
            cartoon-style characters and elements with exaggerated features
            friendly and relatable character designs
            animated cartoon aesthetics with simplified, friendly character designs
    </persona>"""

    # Specific instructions based on content type
    if content_type == "literature":
        type_specific_instructions = """
        <literature_instructions>
            **Style:** Create a prompt for a book cover using vector art, cartoon style, cartoon style.
            Use vivid and vibrant colors, high saturation, dynamic composition. Characters should have exaggerated expressions and be expressive characters.
            It should capture the core themes and emotions of the story summary in a visually appealing, contemporary style.
            **Task:** Based on the provided book summary, create a concise, single-paragraph text-to-image prompt.
            **Suggestion:** If the story has notable characters, consider including them in the cover design as stylized characters with exaggerated expressions that make the cover more engaging and relatable.
            **Knowledge Utilization:** Leverage your existing knowledge about this novel, including its plot, themes, major characters, setting, atmosphere, and literary style to create the most optimal and meaningful image prompt.
        </literature_instructions>"""
    elif content_type == "article":
        type_specific_instructions = """
        <article_instructions>
            **Style:** Modern vector art, cartoon style, cartoon style.
                cartoon-style characters and elements with exaggerated features
                friendly and relatable character designs
                animated cartoon aesthetics with simplified, friendly character designs
            **Content:** The image should be revealing the main topic of the article. and the prompt should be very very very detailed.
            **Task:** Based on the provided article content, create a text-to-image prompt which shows the main topic of the article.
        </article_instructions>"""
    else:
        # A fallback, though the graph logic should prevent this from being used
        type_specific_instructions = """
        <generic_instructions>
            **Style:** Create a prompt for an eye-catching image using vector art, cartoon style, cartoon style.
            Use vivid and vibrant colors, high saturation, dynamic composition. Characters should have exaggerated expressions and be expressive characters.
            **Task:** Create a concise, single-paragraph text-to-image prompt for a generic image.
        </generic_instructions>"""

    guidelines = """
    <guidelines>
        ⚠️ CRITICAL: Your output MUST be a valid JSON object. ⚠️  
        - The entire response must be a single JSON object. Do not add any other text or explanations.
        - Start the response with `{{` and end it with `}}`.
        - The JSON object must contain a single key "prompt" with the generated prompt string as its value.
        - prompt should be under 1024 characters.

        {format_instructions}

    </guidelines>"""

    human_input_variable = "{input}"

    # Combine into the final prompt that will be sent to the text LLM
    final_system_prompt = f"""
    <system_prompt>
        {guidelines}

        Your task is to generate a POSITIVE text prompt that will be used by a text-to-image AI to create a cover image.

        {type_specific_instructions}

        **CRITICAL RULES FOR THE "prompt" VALUE YOU GENERATE:**
        - The prompt you generate should be a single paragraph of descriptive, comma-separated keywords and phrases.
        - **Do not include negative keywords** like 'no text' or 'ugly' in your output. These will be handled by a separate negative prompt.
    </system_prompt>"""

    final_human_prompt = f"""
    <human_prompt>
        {persona_prompt}

        Here is the text to base the image prompt on:

        ---
        {human_input_variable}
        ---

        Make the image prompt as detailed as possible.
    </human_prompt>"""

    chat_prompt = ChatPromptTemplate.from_messages([
        ("system", final_system_prompt),
        ("human", final_human_prompt),
    ])

    return chat_prompt
